os: linux
dist: bionic

addons:
  apt:
    sources:
      - sourceline: 'deb http://us.archive.ubuntu.com/ubuntu/ eoan main'
    packages:
      - libcryptsetup-dev
      - keyutils
      - libkeyutils-dev

language: rust
jobs:
  allow_failures:
    rust: beta
  include:

    # MANDATORY CHECKS USING CURRENT DEVELOPMENT TOOLCHAIN
    - name: "format Rust source using current development toolchain"
      rust: 1.42.0
      before_script:
        - rustup component add rustfmt
      env: TASK=fmt-travis

    - name: "lint Rust source using current development toolchain"
      rust: 1.42.0
      before_script:
        - rustup component add clippy
      env: TASK=clippy

    # MANDATORY TESTING ON STABLE
    - name: "build using stable toolchain"
      rust: stable
      env: TASK=build
    - name: "build Rust docs using stable toolchain"
      rust: stable
      env: TASK=docs-travis
    - name: "run Rust unit tests using stable tool chain"
      rust: stable
      env: TASK=test
    - name: "run Rust loopback unit tests using stable tool chain"
      rust: stable
      script: sudo TEST_DIR=${TRAVIS_HOME} PATH=${TRAVIS_HOME}/.cargo/bin:$PATH make -f Makefile test-loopback
    - name: "build release using stable tool chain"
      rust: stable
      env: TASK=release

branches:
  only:
    - master

script: make -f Makefile $TASK

branches:
  only:
    - master

script: make -f Makefile $TASK
